// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#ifndef RCPP_Rij_RCPPEXPORTS_H_GEN_
#define RCPP_Rij_RCPPEXPORTS_H_GEN_

#include <Rcpp.h>

namespace Rij {

    using namespace Rcpp;

    namespace {
        void validateSignature(const char* sig) {
            Rcpp::Function require = Rcpp::Environment::base_env()["require"];
            require("Rij", Rcpp::Named("quietly") = true);
            typedef int(*Ptr_validate)(const char*);
            static Ptr_validate p_validate = (Ptr_validate)
                R_GetCCallable("Rij", "_Rij_RcppExport_validate");
            if (!p_validate(sig)) {
                throw Rcpp::function_not_exported(
                    "C++ function with signature '" + std::string(sig) + "' not found in Rij");
            }
        }
    }

    inline double cpp_med(Rcpp::NumericVector x) {
        typedef SEXP(*Ptr_cpp_med)(SEXP);
        static Ptr_cpp_med p_cpp_med = NULL;
        if (p_cpp_med == NULL) {
            validateSignature("double(*cpp_med)(Rcpp::NumericVector)");
            p_cpp_med = (Ptr_cpp_med)R_GetCCallable("Rij", "_Rij_cpp_med");
        }
        RObject rcpp_result_gen;
        {
            RNGScope RCPP_rngScope_gen;
            rcpp_result_gen = p_cpp_med(Shield<SEXP>(Rcpp::wrap(x)));
        }
        if (rcpp_result_gen.inherits("interrupted-error"))
            throw Rcpp::internal::InterruptedException();
        if (Rcpp::internal::isLongjumpSentinel(rcpp_result_gen))
            throw Rcpp::LongjumpException(rcpp_result_gen);
        if (rcpp_result_gen.inherits("try-error"))
            throw Rcpp::exception(Rcpp::as<std::string>(rcpp_result_gen).c_str());
        return Rcpp::as<double >(rcpp_result_gen);
    }

}

#endif // RCPP_Rij_RCPPEXPORTS_H_GEN_
